[tox]
min_version = 4.0
env_list = py310, py311, py312, py313

[testenv]
runner = uv-venv-lock-runner
dependency_groups = dev
commands =
    pytest {posargs:test}
    mypy pydoc_fork --ignore-missing-imports
