---
name: Publish pydoc_fork to PyPI
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - uses: hynek/setup-cached-uv@v2
      - name: Install dependencies
        run: uv sync --all-extras
      - name: Run quality gates
        run: uv run make check-ci
      - name: Build package
        run: uv build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: dist/
          if-no-files-found: error
          retention-days: 1
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pydoc_fork
    permissions:
      id-token: write
    needs: build
    steps:
      - name: Fail if branch is not main
        if: github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/main'
        run: |
          echo "This workflow should not be triggered on a branch other than main"
          exit 1
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: 'true'
